### ISSUE TITLE
New pypi-release

### ISSUE THREAD

**Issue by Olen** [kprestel/nextcloud-deck#4]
Sorry to bother you again,

Would you mind updating the pypi-release with the new patches?
I am using this in a docker environment, and it is nice to just pull the packages from pypi instead of copying them from a local repo clone.

Rgds.

**Comment by kprestel** [comment]
Yes, my apologies for not getting to this sooner.  

I want to fix the github action so this doesn't happen again. 

I will have it published for you one way or another this weekend.

**Comment by kprestel** [comment]
I got it working sooner than expected. 

Please try version 0.2.1 on pypi. 

I will leave this issue open until I hear from you that everything is working for you. It looks ok from my POV.
